### ISSUE TITLE
Include `amazon-ecr-credential-helper` in default package list

### ISSUE THREAD

**Issue by diclophis** [CircleCI-Public/cimg-base#110]
Hello,

What is the process for having more default packages including in the base image... specifically I would like to include `amazon-ecr-credential-helper`

**Comment by diclophis** [comment]
I have created the recommended change here: https://github.com/CircleCI-Public/cimg-base/pull/111

**Comment by diclophis** [comment]
@felicianotech I would like to see if this is possible, otherwise I can work with my team to publish our own set of base images as an alternative.

**Comment by felicianotech** [comment]
Hi.

For a community request for a new package to be pre-installed, we look for two things:

1. Will this help a majority of users of this image.
2. Is there demand?

For the first point, I'm not so sure that's the case.
For the second point, having this issue open and/or opening a [CircleCI Idea](https://circleci.canny.io/) will help show demand if we can get votes/+1s on the request.

Alternatively, this might be something that would work well with the AWS ECR orb that we have: https://circleci.com/developer/orbs/orb/circleci/aws-ecr

**Comment by felicianotech** [comment]
I'm going to close the PR for now until there's enough of a demand for this before considering.

**Comment by diclophis** [comment]
At the moment, I won't be able to use the ecr orb until it supports buildkit see: https://github.com/CircleCI-Public/aws-ecr-orb/issues/143

**Comment by Mint-6263** [comment]
@felicianotech

**Comment by diclophis** [comment]
@felicianotech / @Mint-6263 any updates on this ticket?

**Comment by diclophis** [comment]
@felicianotech could we get an update on this ticket... this issue remains a large problem with our build, as we have to always apt-get install this package for every circleci build, this is unnecessary waste in compute credit spend
