### ISSUE TITLE
Investigate the viability of adding Docker's BuildKit into the image

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/cimg-base#147]
This will also be considered for the Linux VM images.

**Comment by diclophis** [comment]
This ticket https://github.com/CircleCI-Public/cimg-base/issues/110 is also related, if we had the ecr helper our org could get by without the ECR orb buildkit support.

**Comment by JalexChen** [comment]
Hi @diclophis, it looks like this will be included as part of the ECR Orb. We'll continue to investigate the use cases of including the ECR helper based on demand, but we would like to keep Buildkit optional at the moment and the Orb is currently being worked on to address that.

**Comment by JalexChen** [comment]
Another note here: @diclophis Currently, we are not looking into adding the ECR helper into this specific image, but we may potentially look into adding an AWS image with that included.

**Comment by diclophis** [comment]
@JalexChen an extra "flavoured" cimg/base with the aws helper included would be a huge win for our org. Thanks!
