### ISSUE TITLE
Where is SSH_CONFIG_DIR set?

### ISSUE THREAD

**Issue by blackliner** [CircleCI-Public/cimg-base#151]
I would assume this image sets this value to `/home/circleci/.ssh`, but it seems to not do so. Where does the default `checkout` find this env variable then? `transparency--`

**Comment by felicianotech** [comment]
This is not set in this image, or even the Linux VM images. The `checkout` step is maintained by a separate team. I'd ask if you can please write your question in a new post on [CircleCI Discuss](https://discuss.circleci.com) and at mention me (FelicianoTech). I can try and get your question sent to the right team so you can get an answer.

In the meantime, I'm going to close this Issue as this is unrelated to this image.
