### ISSUE TITLE
Add Retry Command

### ISSUE THREAD

**Issue by felixshiftellecon** [CircleCI-Public/cimg-base#222]
Often users need to retry commands due to hiccups, flakiness, etc. It would be helpful if a retry command was added to this base image similar to this one](https://github.com/kadwanev/retry).

**Comment by felicianotech** [comment]
Hi. This sounds reasonable. We will likely consider adding something like this but it will take a little bit to determine which project/command we actually want. I'm not sold on the one provided. I'm aiming to get this resolved before the February release of this image.

**Comment by BytesGuy** [comment]
A retry command will be included in cimg base moving forward. It is the version installable via default ubuntu apt repos as this seemed to be the most appropriate and provides similar functionality to the one previously linked: https://packages.ubuntu.com/jammy/retry
