### ISSUE TITLE
Ship a `circleci` system user

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/cimg-base#35]
The Next-Gen images were suppose to ship with just a `root` user. That was the plan.

The security gains by using a regular user with sudo access are irrelevant in the world of Docker because:

1. With `sudo` they get root privileges anyway
2. With passwordless sudo, there's no additional security of a password.

Due to legacy image migration concerns, having sudo around would be useful. I'm not sure if useful enough on its own, but there are CircleCI platform features that expect to see a circleci home directory.

With little negative affect to our images and lots of positive affect for migration, we should reintroduce the `circleci` user to images.

**Comment by eddiewebb** [comment]
Other impact besides `sudo` is anyone caching directories in user's home are restored as an absolute path will all be misses when they move from `/home/circleci` to `/root`

![Screen Shot 2019-12-18 at 4 13 56 PM](https://user-images.githubusercontent.com/5262154/71123847-8b680700-21b1-11ea-854e-76a9c9866bf6.png)
