### ISSUE TITLE
`docker version` command fails due to daemon connection

### ISSUE THREAD

**Issue by huntie** [CircleCI-Public/cimg-base#36]
As I understand, this image should include both Docker and Docker Compose. When I run `docker version` in a job, it fails with the following error; it appears the Docker daemon isn't started or is misconfigured.

```sh
#!/bin/bash -eo pipefail
docker version
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:29:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by iynere** [comment]
hi @huntie, as in our previous set of convenience images, you will need to run `setup_remote_docker` first in order to use a docker daemon in any docker image-based execution environments:

https://circleci.com/docs/2.0/configuration-reference/#setup_remote_docker
