### ISSUE TITLE
Checkout step failed

### ISSUE THREAD

**Issue by asdwsda** [CircleCI-Public/cimg-base#40]
Checkout step failed to git clone, because `project` dir is owned by `root` and not writable by `circleci`.

```
Cloning into '.'...
/home/circleci/project/.git: Permission denied

exit status 1
```

```
circleci@9405c3127ad2:~$ ls -ld /home/circleci/project/
drwxr-xr-x 2 root root 4096 Jan  2 00:04 /home/circleci/project/
```

Image version:
```
Status: Downloaded newer image for cimg/base:stable
  using image cimg/base@sha256:563d629e330773aae63e800b431500761bf1597a765de5c9d92529ddadb330b7
```

**Comment by asdwsda** [comment]
According to the **docker** documentation, `USER` only affects `RUN`, `CMD` and `ENTRYPOINT`

```
The USER instruction sets the user name (or UID) and optionally the user group (or GID) to use when running the image and for any RUN, CMD and ENTRYPOINT instructions that follow it in the Dockerfile.
```

**Comment by felicianotech** [comment]
@asdwsda Hey. Can you confirm this was fixed for you?

**Comment by asdwsda** [comment]
> @asdwsda Hey. Can you confirm this was fixed for you?

Yes, it works now! Thanks @felicianotech

**Comment by felicianotech** [comment]
Awesome. Thanks for opening this issue.

**Comment by HolimaX** [comment]
Possible regression: https://github.com/CircleCI-Public/cimg-go/issues/158
