### ISSUE TITLE
Include libs for popular databases?

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/cimg-base#60]
When using the Docker executor, it's commonplace for CircleCI 2.0+ to use secondary/service images for databases such as MariaDB and PostgreSQL rather than having that database installed in the primary image itself. This is how the legacy images operate to this day.

To connect to the database, it's done over TCP, a private IP between the primary and secondary container.

For some apps, such as a Ruby app, connecting to the DB is typically done with the `pg` gem. This gem requires `libpq-dev` installed in order to work. Other languages can have similar needs for both PostgreSQL and other DBs.

Some of our legacy images (such as `circleci/ruby`) has this lib installed and some don't.

**How should we handle this?**

We can:

1. have a user just install it if they need it
2. pre-install this lib (and similar) in the base image so that all language images get it
3. pre-install it in specific language images on a case-by-case basis
4. take care of it in an orb

Solutions 2-3 cause image sizes to rise. We likely can't just cater to one DB, so then we should add more. More being... all the DBs we officially support in images? That's about 5.

Solution 4 I like because we can also install the CLIs for these DBs as well which some may prefer. Gives up flexibility there and keeps the images lean. The downside is another step up front for a user to setup and it will slightly add to a job's runtime.

Thoughts? Opinions?

**Comment by louim** [comment]
I can understand the appeal of having slim images. My honest opinion as a end user is that I want something that works. Main thing I look for in builds is speed. I don't mind if that's a separate step or not as long as it's well documented **and** it's faster. It's likely something that I will do setup once per project. What I don't want is something adding 15 seconds (I choose a totally random number here) only for the sake of having a smaller base image 😄.

**Comment by felicianotech** [comment]
Here's the idea on being strict on what enters the image. Keep in mind, I'm not speaking specifically about `libpq` here, which I'm leaning on including. This is the general philosophy.

> What I don't want is something adding 15 seconds (I choose a totally random number here) to the build time, only for the sake of having a smaller base image

Having a smaller base image isn't about it literally being small. A smaller, less layers image downloads faster and is also less maintenance for our team (depending on what's added). The scenario we are trying to prevent is adding a bunch of tools that saves 20% of our users 15 seconds by increasing the download time for the image by 10 seconds for 80% of users.

**Comment by louim** [comment]
@felicianotech that's totally reasonable. Apologies if my previous comment sounded aggressive, that was not the intention.

**Comment by felicianotech** [comment]
Not at all. Your feedback is very helpful. I just only hope we can get some more to share their opinions. If we do start adding in some database libs, I hope to get this in this month so it makes the June snapshot image.
